cscript.exe glsl_stringify.vbs iortcw\MP\code\rend2\glsl\bokeh_fp.glsl        glsl_to_c\bokeh_fp.c
cscript.exe glsl_stringify.vbs iortcw\MP\code\rend2\glsl\bokeh_vp.glsl        glsl_to_c\bokeh_vp.c
cscript.exe glsl_stringify.vbs iortcw\MP\code\rend2\glsl\calclevels4x_fp.glsl glsl_to_c\calclevels4x_fp.c
cscript.exe glsl_stringify.vbs iortcw\MP\code\rend2\glsl\calclevels4x_vp.glsl glsl_to_c\calclevels4x_vp.c
cscript.exe glsl_stringify.vbs iortcw\MP\code\rend2\glsl\depthblur_fp.glsl    glsl_to_c\depthblur_fp.c
cscript.exe glsl_stringify.vbs iortcw\MP\code\rend2\glsl\depthblur_vp.glsl    glsl_to_c\depthblur_vp.c
cscript.exe glsl_stringify.vbs iortcw\MP\code\rend2\glsl\dlight_fp.glsl       glsl_to_c\dlight_fp.c
cscript.exe glsl_stringify.vbs iortcw\MP\code\rend2\glsl\dlight_vp.glsl       glsl_to_c\dlight_vp.c
cscript.exe glsl_stringify.vbs iortcw\MP\code\rend2\glsl\down4x_fp.glsl       glsl_to_c\down4x_fp.c
cscript.exe glsl_stringify.vbs iortcw\MP\code\rend2\glsl\down4x_vp.glsl       glsl_to_c\down4x_vp.c
cscript.exe glsl_stringify.vbs iortcw\MP\code\rend2\glsl\fogpass_fp.glsl      glsl_to_c\fogpass_fp.c
cscript.exe glsl_stringify.vbs iortcw\MP\code\rend2\glsl\fogpass_vp.glsl      glsl_to_c\fogpass_vp.c
cscript.exe glsl_stringify.vbs iortcw\MP\code\rend2\glsl\generic_fp.glsl      glsl_to_c\generic_fp.c
cscript.exe glsl_stringify.vbs iortcw\MP\code\rend2\glsl\generic_vp.glsl      glsl_to_c\generic_vp.c
cscript.exe glsl_stringify.vbs iortcw\MP\code\rend2\glsl\lightall_fp.glsl     glsl_to_c\lightall_fp.c
cscript.exe glsl_stringify.vbs iortcw\MP\code\rend2\glsl\lightall_vp.glsl     glsl_to_c\lightall_vp.c
cscript.exe glsl_stringify.vbs iortcw\MP\code\rend2\glsl\pshadow_fp.glsl      glsl_to_c\pshadow_fp.c
cscript.exe glsl_stringify.vbs iortcw\MP\code\rend2\glsl\pshadow_vp.glsl      glsl_to_c\pshadow_vp.c
cscript.exe glsl_stringify.vbs iortcw\MP\code\rend2\glsl\shadowfill_fp.glsl   glsl_to_c\shadowfill_fp.c
cscript.exe glsl_stringify.vbs iortcw\MP\code\rend2\glsl\shadowfill_vp.glsl   glsl_to_c\shadowfill_vp.c
cscript.exe glsl_stringify.vbs iortcw\MP\code\rend2\glsl\shadowmask_fp.glsl   glsl_to_c\shadowmask_fp.c
cscript.exe glsl_stringify.vbs iortcw\MP\code\rend2\glsl\shadowmask_vp.glsl   glsl_to_c\shadowmask_vp.c
cscript.exe glsl_stringify.vbs iortcw\MP\code\rend2\glsl\ssao_fp.glsl         glsl_to_c\ssao_fp.c
cscript.exe glsl_stringify.vbs iortcw\MP\code\rend2\glsl\ssao_vp.glsl         glsl_to_c\ssao_vp.c
cscript.exe glsl_stringify.vbs iortcw\MP\code\rend2\glsl\texturecolor_fp.glsl glsl_to_c\texturecolor_fp.c
cscript.exe glsl_stringify.vbs iortcw\MP\code\rend2\glsl\texturecolor_vp.glsl glsl_to_c\texturecolor_vp.c
cscript.exe glsl_stringify.vbs iortcw\MP\code\rend2\glsl\tonemap_fp.glsl      glsl_to_c\tonemap_fp.c
cscript.exe glsl_stringify.vbs iortcw\MP\code\rend2\glsl\tonemap_vp.glsl      glsl_to_c\tonemap_vp.c